export default {
  DATA_LOADED: "DATA_LOADED",
  LOADING_DATA: "LOADING DATA",
  ERROR_LOADING_DATA: "ERROR LOADING DATA",
  
  ADDING_IMAGE: "ADDING_IMAGE",
  ADDITION_FAILED: "ADDITION_FAILED",
  ADDITION_SUCCEDED: "ADDITION_SUCCEDED",
  
};
